services:
  rl-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl-dev
    privileged: true
    command: /bin/bash
    stdin_open: true
    runtime: nvidia
    volumes:
      - ../:/reinforcement-learning-fb
    tty: true # Keeps the container running interactively
